---
title: "Sports Crime 2026 Report"
author: "Addina Rahaman and Alexie"
date: '`r Sys.time()`'
output:
  html_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(here)
library(scales)
library(tidyverse)
library(cfbfastR)
```

```{r}

offenses <- read_csv(here('offense_segment.csv'))
batches <- read_csv(here('nibrs_batch_header_1991_2024.csv')) %>% 
  filter(grepl('200[0-5]', year))
```

```{r}
university_ori_lookup <- tribble(
  ~university, ~city_name, ~ori,
  'the university of akron', 'akron', 'OH0772800',
  'iowa state university', 'ames', 'IA0850100',
  'the university of michigan', 'ann arbor', 'MI8190300',
  'ohio university', 'athens', 'OH0050100',
  'the university of texas at austin', 'austin', 'TX2270500',
  'virginia polytechnic institute and state university', 'blacksburg', 'VA0600100',
  'boise state university', 'boise', 'ID0010100',
  'clemson university', 'clemson', 'SC0390600', 
  'united states air force academy', 'colorado springs', 'CO0210100',
  'the university of south carolina', 'columbia', 'SC0400600',
  'the ohio state university', 'columbus', 'OH0252700',
  'the university of north texas', 'denton', 'TX0611100',
  'michigan state university', 'east lansing', 'MI3336400',
  'university of arkansas', 'fayetteville', 'AR0720400',
  'marshall university', 'huntington', 'WV0060200',
  'the university of iowa', 'iowa city', 'IA0520400',
  'arkansas state university', 'jonesboro', 'AR0160500',
  'western michigan university', 'kalamazoo', 'MI3949900',
  'the university of kansas', 'lawrence', 'KS0230100',
  'utah state university', 'logan', 'UT0031600',
  'texas tech university', 'lubbock', 'TX1520600',
  'west virginia university', 'morgantown', 'WV0310100',
  'the university of idaho', 'moscow', 'ID0290500', 
  'eastern michigan university', 'mount pleasant', 'MI3759900',
  'middle tennessee state university', 'murfreesboro', 'TN0750100',
  'brigham young university', 'provo', 'UT0250600'
)

batches_filtered <- university_ori_lookup %>% 
  left_join(batches_filtered, by=c('ori', 'city_name'))

```

```{r}
offenses_filtered <- batches_filtered %>% 
  left_join(offenses) %>% 
  drop_na(year)

# All the assault and vandalism cases
offenses_filtered <- offenses_filtered %>%
 filter(grepl('assault|vandalism', ucr_offense_code, ignore.case=TRUE))
```

```{r}
game_schedule_raw <- c()
years <- 2000:2005

for (year in years) {
  i = year %% 2000 + 1
  game_schedule_raw[[i]] = espn_cfb_schedule(
    year = year
  )
}

names(game_schedule_raw) = c('2000', '2001', '2002', '2003', '2004', '2005')

game_schedule <- bind_rows(game_schedule_raw, .id='year')

game_schedule <- game_schedule %>% 
  mutate(
    home_team_name = case_when(
      home_team_id == "2711" ~ "Broncos2", # Boise and western michigan have the same team name so im replacing western michigan with Broncos2
      TRUE ~ home_team_name
    )
  )
```

```{r}
university_team_lookup <- tribble(
  ~university, ~home_team_name,
  'the university of akron', 'Zips',
  'iowa state university', 'Cyclones',
  'the university of michigan', 'Wolverines',
  'ohio university', 'Bobcats', 
  'the university of texas at austin', 'Longhorns',
  'virginia polytechnic institute and state university', 'Hokies',
  'boise state university', 'Broncos',
  'clemson university', 'Tigers',
  'united states air force academy', 'Falcons',
  'the university of south carolina', 'Gamecocks',
  'the ohio state university', 'Buckeyes',
  'the university of north texas', 'Mean Green',
  'michigan state university', 'Spartans',
  'university of arkansas', 'Razorbacks',
  'marshall university', 'Thundering Herd',
  'the university of iowa', 'Hawkeyes',
  'arkansas state university', 'Red Wolves', 
  'western michigan university', 'Broncos2',
  'the university of kansas', 'Jayhawks',
  'utah state university', 'Aggies', 
  'texas tech university', 'Red Raiders',
  'west virginia university', 'Mountaineers',
  'the university of idaho', 'Vandals',
  'eastern michigan university', 'Eagles',
  'middle tennessee state university', 'Blue Raiders',
  'brigham young university', 'Cougars' 
)

offenses_filtered2 <- offenses_filtered %>% 
  left_join(university_team_lookup, by='university') %>% 
  mutate(year=as.character(year)) %>%
  left_join(game_schedule)
         
# > names(offenses_filtered2)
#   [1] "university"                       "city_name"                       
#   [3] "ori"                              "year"                            
#   [5] "state"                            "population"                      
#   [7] "date_ori_was_added"               "date_ori_went_nibrs"             
#   [9] "state_abbreviation"               "population_group"                
#  [11] "country_division"                 "country_region"                  
#  [13] "agency_indicator"                 "core_city"                       
#  [15] "covered_by_ori"                   "fbi_field_office"                
#  [17] "judicial_district"                "agency_nibrs_flag"               
#  [19] "agency_inactive_date"             "current_population_1"            
#  [21] "ucr_county_code_1"                "msa_code_1"                      
#  [23] "last_population_1"                "current_population_2"            
#  [25] "ucr_county_code_2"                "msa_code_2"                      
#  [27] "last_population_2"                "current_population_3"            
#  [29] "ucr_county_code_3"                "msa_code_3"                      
#  [31] "last_population_3"                "current_population_4"            
#  [33] "ucr_county_code_4"                "msa_code_4"                      
#  [35] "last_population_4"                "current_population_5"            
#  [37] "ucr_county_code_5"                "msa_code_5"                      
#  [39] "last_population_5"                "x01_06_12_indicator"             
#  [41] "number_of_months_reported"        "master_file_year"                
#  [43] "january_zero_report_submitted"    "january_group_a_b_submitted"     
#  [45] "january_window_record_submitted"  "february_zero_report_submitted"  
#  [47] "february_group_a_b_submitted"     "february_window_record_submitted"
#  [49] "march_zero_report_submitted"      "march_group_a_b_submitted"       
#  [51] "march_window_record_submitted"    "april_zero_report_submitted"     
#  [53] "april_group_a_b_submitted"        "april_window_record_submitted"   
#  [55] "may_zero_report_submitted"        "may_group_a_b_submitted"         
#  [57] "may_window_record_submitted"      "june_zero_report_submitted"      
#  [59] "june_group_a_b_submitted"         "june_window_record_submitted"    
#  [61] "july_zero_report_submitted"       "july_group_a_b_submitted"        
#  [63] "july_window_record_submitted"     "august_zero_report_submitted"    
#  [65] "august_group_a_b_submitted"       "august_window_record_submitted"  
#  [67] "september_zero_report_submitted"  "september_group_a_b_submitted"   
#  [69] "september_window_record_submitte" "october_zero_report_submitted"   
#  [71] "october_group_a_b_submitted"      "october_window_record_submitted" 
#  [73] "november_zero_report_submitted"   "november_group_a_b_submitted"    
#  [75] "november_window_record_submitted" "december_zero_report_submitted"  
#  [77] "december_group_a_b_submitted"     "december_window_record_submitted"
#  [79] "fips_county_code_1"               "fips_county_code_2"              
#  [81] "fips_county_code_3"               "fips_county_code_4"              
#  [83] "fips_county_code_5"               "state_abb"                       
#  [85] "incident_number"                  "incident_date"                   
#  [87] "ucr_offense_code"                 "offense_attempted_or_completed"  
#  [89] "offender_suspected_of_using_1"    "offender_suspected_of_using_2"   
#  [91] "offender_suspected_of_using_3"    "location_type"                   
#  [93] "number_of_premises_entered"       "method_of_entry"                 
#  [95] "type_criminal_activity_1"         "type_criminal_activity_2"        
#  [97] "type_criminal_activity_3"         "type_weapon_force_involved_1"    
#  [99] "automatic_weapon_indicator_1"     "type_weapon_force_involved_2"    
# [101] "automatic_weapon_indicator_2"     "type_weapon_force_involved_3"    
# [103] "automatic_weapon_indicator_3"     "bias_motivation"                 
# [105] "unique_incident_id"               "home_team_name"                  
# [107] "matchup"                          "matchup_short"                   
# [109] "season"                           "type"                            
# [111] "slug"                             "game_id"                         
# [113] "game_uid"                         "game_date"                       
# [115] "attendance"                       "date_valid"                      
# [117] "play_by_play_available"           "home_team_logo"                  
# [119] "home_team_abb"                    "home_team_id"                    
# [121] "home_team_location"               "home_team_full"                  
# [123] "home_team_color"                  "home_score"                      
# [125] "home_win"                         "home_record"                     
# [127] "away_team_name"                   "away_team_logo"                  
# [129] "away_team_abb"                    "away_team_id"                    
# [131] "away_team_location"               "away_team_full"                  
# [133] "away_team_color"                  "away_score"                      
# [135] "away_win"                         "away_record"                     
# [137] "status_name"                      "broadcasts"                      
# [139] "start_date"                       "broadcast"                       
# [141] "geo_broadcasts"                   "highlights"                      
# [143] "game_date_time"                   "notes"                           
# [145] "broadcast_market"                 "broadcast_name"                  
# [147] "passing_leader_yards"             "passing_leader_stat"             
# [149] "passing_leader_name"              "passing_leader_shortname"        
# [151] "passing_leader_headshot"          "passing_leader_team_id"          
# [153] "passing_leader_pos"               "rushing_leader_yards"            
# [155] "rushing_leader_stat"              "rushing_leader_name"             
# [157] "rushing_leader_shortname"         "rushing_leader_headshot"         
# [159] "rushing_leader_team_id"           "rushing_leader_pos"              
# [161] "receiving_leader_yards"           "receiving_leader_stat"           
# [163] "receiving_leader_name"            "receiving_leader_shortname"      
# [165] "receiving_leader_headshot"        "receiving_leader_team_id"        
# [167] "receiving_leader_pos"    
```

```{r}
# just a way to view the ori, university, and home_team_name mappings
offenses_filtered2 %>% 
  select(ori, home_team_name, university) %>%
  unique()

# create a column that classifies by no game, home game, and away game
agency_days <- offenses_filtered %>% 
  filter((grepl('^200[0-5]-', incident_date))) %>%
  group_by(ori, incident_date) %>% 
  summarize(
    number_of_offenses=n()
  )

game_schedule_filtered <- game_schedule %>% 
  select(year, matchup, season, )

```

